services:
  videmus-nextjs:
    image: daiius/private-registry:videmus-nextjs
    container_name: videmus-nextjs
    volumes: !reset
  videmus-resource-server:
    image: daiius/private-registry:videmus-resource-server
    volumes: !reset
  videmus-media-server:
    image: daiius/private-registry:videmus-media-server
    volumes: !reset
