services:
  videmus-nextjs:
    build:
      dockerfile: ./next/Dockerfile.nextjs
    container_name: videmus-nextjs-dev
    working_dir: /workspace/next
    environment:
      TZ: 'Asia/Tokyo'
    env_file:
      - .env.next
      - .env.database
    volumes:
      - ./database:/workspace/database
      - /workspace/database/node_modules
      - ./next:/workspace/next
      - /workspace/next/node_modules
    tmpfs:
      - /workspace/app/.next

  videmus-webrtc:
    build:
      dockerfile: ./webrtc/Dockerfile.webrtc
    container_name: videmus-webrtc
    working_dir: /workspace/app
    env_file:
      - .env.webrtc
      - .env.database
    environment:
      DEBUG: "mediasoup*,videmus:webrtc*"
      TZ: 'Asia/Tokyo'
    ports:
      - 44400:44400/udp
    volumes:
      - ./database:/workspace/database
      - /workspace/database/node_modules
      - ./webrtc:/workspace/app
      - /workspace/app/node_modules
    depends_on:
      database-preparation:
        condition: service_completed_successfully 

  webserver:
    image: nginx
    container_name: videmus-webserver
    ports:
      - 80:80
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      database-preparation:
        condition: service_completed_successfully 

  database:
    image: mysql:8.4
    container_name: videmus-database
    environment:
      TZ: 'Asia/Tokyo'
      LANG: 'ja_JP.UTF-8'
    env_file:
      - .env.database
    tmpfs:
      - /var/lib/mysql # テスト用、データは毎回削除される
    cap_add:
      - SYS_NICE
    healthcheck:
      test: mysql -u $$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE -e "select 1;"
      interval: 5s
      timeout: 20s
      retries: 3
      start_period: 5s

  database-preparation:
    build:
      dockerfile: database/Dockerfile.database-preparation
    container_name: videmus-database-preparation
    working_dir: /workspace/database
    env_file:
      - .env.database
    volumes:
      - ./database:/workspace/database
      - /workspace/database/node_modules
    command: >
      bash -c '
        pnpm drizzle-kit push \
             --dialect mysql \
             --schema=./db/schema.ts \
             --host=$$DB_HOST \
             --user=$$MYSQL_USER \
             --password=$$MYSQL_PASSWORD \
             --database=$$MYSQL_DATABASE && \
        pnpm tsx addTestData.ts
      '
    depends_on:
      database:
        condition: service_healthy

networks:
  default:
    name: videmus-network 

