services:
  videmus-nextjs:
    build:
      dockerfile: ./next/Dockerfile.nextjs
    container_name: videmus-nextjs-dev
    working_dir: /workspace/next
    environment:
      TZ: 'Asia/Tokyo'
    env_file:
      - .env.next
      - .env.database
    ports:
      - 3000:3000
    volumes:
      - ./database:/workspace/database
      - /workspace/database/node_modules
      - ./next:/workspace/next
      - /workspace/next/node_modules
      - ./resource-server:/workspace/resource-server
      - /workspace/resource-server/node_modules
      - /workspace/node_modules
    tmpfs:
      - /workspace/app/.next

  videmus-resource-server:
    build:
      dockerfile: ./resource-server/Dockerfile.resource-server
    container_name: videmus-resource-server
    working_dir: /workspace/resource-server
    env_file:
      - .env.resource-server
      - .env.database
    environment:
      DEBUG: "videmus:resource-server*"
      TZ: 'Asia/Tokyo'
      MEDIA_SERVER_URL: http://videmus-media-server:4001
    ports:
      - 4000:4000
    volumes:
      - ./database:/workspace/database
      - /workspace/database/node_modules
      - ./resource-server:/workspace/resource-server
      - /workspace/resource-server/node_modules
      - /workspace/node_modules
    depends_on:
      database-preparation:
        condition: service_completed_successfully

  videmus-media-server:
    build:
      dockerfile: ./media-server/Dockerfile.media-server
    container_name: videmus-media-server
    working_dir: /workspace/media-server
    env_file:
      - .env.media-server
    environment:
      DEBUG: "mediasoup*,videmus:media-server*"
      TZ: 'Asia/Tokyo'
      DTLS_CERT: ./dtls-cert.pem
      DTLS_KEY: ./dtls-key.pem
      API_URL: http://videmus-resource-server:4000
    ports:
      - 4001:4001
      - 44400:44400/udp
      - 44400:44400/tcp
      - "50000-50010:50000-50010/udp"
    volumes:
      - ./media-server:/workspace/media-server
      - /workspace/media-server/node_modules
      - /workspace/node_modules
      - ./media-server/dtls-cert.pem:/workspace/media-server/dtls-cert.pem
      - ./media-server/dtls-key.pem:/workspace/media-server/dtls-key.pem

  database:
    image: mysql:8.4
    container_name: videmus-database
    environment:
      TZ: 'Asia/Tokyo'
      LANG: 'ja_JP.UTF-8'
    env_file:
      - .env.database
    tmpfs:
      - /var/lib/mysql # テスト用、データは毎回削除される
    cap_add:
      - SYS_NICE
    healthcheck:
      test: mysql -u $$MYSQL_USER -p$$MYSQL_PASSWORD $$MYSQL_DATABASE -e "select 1;"
      interval: 5s
      timeout: 20s
      retries: 3
      start_period: 5s

  database-preparation:
    build:
      dockerfile: database/Dockerfile.database-preparation
    container_name: videmus-database-preparation
    working_dir: /workspace/database
    env_file:
      - .env.database
    volumes:
      - ./database:/workspace/database
      - /workspace/database/node_modules
      - /workspace/node_modules
    command: >
      bash -c '
        pnpm drizzle-kit push \
             --dialect mysql \
             --schema=./db/schema.ts \
             --host=$$DB_HOST \
             --user=$$MYSQL_USER \
             --password=$$MYSQL_PASSWORD \
             --database=$$MYSQL_DATABASE && \
        pnpm tsx addTestData.ts
      '
    depends_on:
      database:
        condition: service_healthy

networks:
  default:
    name: videmus-network
