FROM node:20-slim

WORKDIR /workspace/resource-server

RUN npm install -g pnpm

# monorepo root
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml /workspace/
# monorepo database
COPY database/package.json /workspace/database/
# monorepo resource-server
COPY resource-server/package.json resource-server/tsconfig.json /workspace/resource-server/

RUN pnpm install --filter videmus-resource-server --filter videmus-database


CMD ["pnpm", "dev"]
