FROM node:20

WORKDIR /workspace/app

RUN npm install -g pnpm


# 本当はコンテナ内でしたいが、モノレポ構成だと厳しいかも
# (workspaceやsymbolic linkになったパッケージを参照できるか？)
#COPY package.json .
#RUN pnpm install

CMD ["pnpm", "dev"]

