FROM node:20-slim

WORKDIR /workspace/app

RUN npm install -g pnpm

# monorepo root
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml /workspace/
# monorepo database
COPY database/package.json /workspace/database/
# monorepo nextjs
COPY webrtc/package.json webrtc/tsconfig.json /workspace/app/

RUN pnpm install


CMD ["pnpm", "dev"]

